### PR TITLE
Release candidate 1.0

### PR DESCRIPTION
**Pull request by bsamseth**
Candidate for a 1.0 release. The core formatting rules haven't changed for a good while, and seem to work well against Databricks' notebook format. I also want to remove the black-patching to use two spaces for indentation, now that Databricks is no longer forcing 2 spaces. Doing so _will_ be a breaking change, which is a good time to bump the major version.

Biggest changes:

- Change of default indentation to 4 spaces.
- Option for using four spaces will be deprecated.
- Removal of option for using two spaces for indentation.
- New help and error formatting, courtesy of using a newer version of typer.
- ~~Drop support for Python 3.8 and below. It's been long enough since 3.9 was released~~

Version 0.7.0 deprecated two-space indentation on 2022-09-03. In order to give users a chance to notice the deprecation warning, version 1.0 is scheduled for release on 2022-09-11. That's not a big window, but both from the 0.x version and the beta tag on PyPI there was never a guarantee of stability.

### CODE REVIEW

**Comment by NodeJSmith** [comment]
@bsamseth I have a concern about dropping support for Python 3.8. The Databricks 10.4 runtime is their latest LTS, and it uses 3.8.10. Dropping support for 3.8 would make it much harder to use this package in an environment set up to develop for the 10.4 runtime.

Is there a large need to remove support for 3.8?

**Comment by bsamseth** [comment]
@NodeJSmith That's a fair point. I've never actually used blackbricks from a Databricks cluster, so I didn't even consider this. I have it installed as a binary locally, and never felt the need to have it elsewhere.

The main reason for dropping support for 3.8 is maintenance. I was concerned about _accidentally_ using a 3.9+ feature without thinking about it, and not noticing because I don't use 3.8 on my machine anymore. I figured it was better to explicitly not support it. 

However, my guess is that you are not alone in this. I'm inclined to keep 3.8 support because of it, at least until the next LTS has been out for a while.

Out of curiosity, what is is the benefit of having it installed on the cluster in your mind? Blackbricks is an application, not a library, so the dependency requirements are intentionally made rather strict to ensure it works correctly. Assuming you install it through the libraries tab in the cluster config, that would likely cause dependency conflicts whenever you install a library that shares some dependencies with blackbricks. Perhaps this simply hasn't come up as an issue in your case?

**Comment by NodeJSmith** [comment]
@bsamseth We are not using blackbricks on the cluster itself, but we create virtual environments for development with the same Python runtime as our job clusters use. This means that we always run Python 3.8.10 locally, which is where we would be installing and running blackbricks from. We won't be able to use blackbricks the way we currently are, if support for 3.8 is dropped.

image

**Comment by bsamseth** [comment]
@NodeJSmith That makes more sense, thanks. I would still worry that you could get dependency conflicts with this approach, but if that isn't an issue then I see the benefit of bundling up everything for the sake of consistency. 

I've restored 3.8 compatibility in [fc2eed8](https://github.com/inspera/blackbricks/pull/25/commits/fc2eed88e368eb77dc0fc82f5f8dc916c3ecb143).

**Pull request merged**
